import ChatComponent from '@/components/ChatComponent'
import Footer from '@/components/dashboard/Footer'
import Navbar from '@/components/dashboard/Narbar'
import Sidebar from '@/components/dashboard/Sidebar'
import type { Metadata } from 'next'
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      <div className="flex flex-grow">
        <Sidebar />
        <main className="py-4 bg-gray-50 w-full">{children}</main>
      </div>
      <Footer />
      <ChatComponent />
    </div>
  )
}
